export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TENANT_REQUIRED: 'TENANT_REQUIRED',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  STALE_VERSION: 'STALE_VERSION',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',
  REFRESH_REUSE: 'REFRESH_REUSE',
  OTP_INVALID: 'OTP_INVALID',
  PASSWORD_POLICY: 'PASSWORD_POLICY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ErrorTypes: Record<ErrorCode, string> = {
  VALIDATION_ERROR: 'https://docs.intraleads.example/errors/validation',
  BAD_REQUEST: 'https://docs.intraleads.example/errors/bad-request',
  UNAUTHORIZED: 'https://docs.intraleads.example/errors/unauthorized',
  FORBIDDEN: 'https://docs.intraleads.example/errors/forbidden',
  NOT_FOUND: 'https://docs.intraleads.example/errors/not-found',
  CONFLICT: 'https://docs.intraleads.example/errors/conflict',
  RATE_LIMITED: 'https://docs.intraleads.example/errors/rate-limited',
  INTERNAL_ERROR: 'https://docs.intraleads.example/errors/internal',
  SERVICE_UNAVAILABLE: 'https://docs.intraleads.example/errors/unavailable',
  TENANT_REQUIRED: 'https://docs.intraleads.example/errors/tenant-required',
  TENANT_MISMATCH: 'https://docs.intraleads.example/errors/tenant-mismatch',
  IDEMPOTENCY_CONFLICT: 'https://docs.intraleads.example/errors/idempotency',
  STALE_VERSION: 'https://docs.intraleads.example/errors/stale-version',
  ACCOUNT_LOCKED: 'https://docs.intraleads.example/errors/account-locked',
  INVALID_CREDENTIALS: 'https://docs.intraleads.example/errors/invalid-credentials',
  SESSION_EXPIRED: 'https://docs.intraleads.example/errors/session-expired',
  DEVICE_MISMATCH: 'https://docs.intraleads.example/errors/device-mismatch',
  REFRESH_REUSE: 'https://docs.intraleads.example/errors/refresh-reuse',
  OTP_INVALID: 'https://docs.intraleads.example/errors/otp-invalid',
  PASSWORD_POLICY: 'https://docs.intraleads.example/errors/password-policy',
};
